### PR TITLE
Adds command: pod reinstall

### PR DESCRIPTION
**Pull request by markrickert**
This command will run `pod install` and output the results of the command in realtime and then run `pod open`.

Thought it was a good companion to `pod open` since I find myself often closing xcode, adjusting the Podfile, and then running `pod install && pod open`.

### CODE REVIEW

**Comment by leshill** [comment]
Hi @markrickert,

Looks great. Thanks!

**Comment by markrickert** [comment]
Awesome! Thanks for accepting the PR! I started using this gem today and thought this would be a great addition.

**Comment by markrickert** [comment]
The toughest part was getting the system command to output the results from `pod install` in realtime.

**Comment by soffes** [comment]
Good idea, @markrickert!

**Pull request merged**
